apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: imagetests.imagetest.tarmak.io
spec:
  group: imagetest.tarmak.io
  names:
    kind: ImageTest
    plural: imagetests
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              properties:
                location:
                  type: string
                name:
                  type: string
              type: object
            source:
              properties:
                image:
                  properties:
                    location:
                      type: string
                    name:
                      type: string
                  type: object
                tarmakVersion:
                  type: string
              type: object
            tarmakVersion:
              type: string
          type: object
        status:
          properties:
            state:
              type: string
            testConditions:
              items:
                properties:
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
